config/routes.rb
Rails.application.routes.draw do
  resource  :session
  resources :examples

  resources :messages do
    resources :comments
  end

  root 'examples#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user

  after_commit { CommentRelayJob.perform_later(self) }
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_message

  def create
    @comment = Comment.create! content: params[:comment][:content], message: @message, user: @current_user
  end

  private
    def set_message
      @message = Message.find(params[:message_id])
    end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern
  
  included do
    before_action :ensure_authenticated_user
  end

  private
    def ensure_authenticated_user
      authenticate_user(cookies.signed[:user_id]) || redirect_to(new_session_url)
    end

    def authenticate_user(user_id)
      if authenticated_user = User.find_by(id: user_id)
        cookies.signed[:user_id] ||= user_id
        @current_user = authenticated_user
      end
    end

    def unauthenticate_user
      ActionCable.server.disconnect(current_user: @current_user)
      @current_user = nil
      cookies.delete(:user_id)
    end
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_authenticated_user, only: %i( new create )

  def new
    @users = User.all
  end

  def create
    authenticate_user(params[:user_id])
    redirect_to examples_url
  end

  def destroy
    unauthenticate_user
    redirect_to new_session_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<article data-user-id="<%= comment.user.id %>">
  <h3>Comment by <%= comment.user.name %></h3>
  <p><%= comment.content %></p>
</article>

app/views/comments/_comments.html.erb
<section id="comments" data-channel="comments" data-message-id="<%= message.id %>">
  <%= render message.comments %>
</section>

<%= render 'comments/new', message: message %>

app/views/comments/_new.html.erb
<%= form_for [ message, Comment.new ], remote: true do |form| %>
  <%= form.text_area :content, size: '100x20' %><br>
  <%= form.submit 'Post comment' %>
<% end %>

app/views/comments/create.js.erb
$('#comments').append('<%=j render @comment %>');
$('#new_comment').replaceWith('<%=j render 'comments/new', message: @message %>');

app/views/examples/index.html.erb
<h1>Action Cable Examples</h1>

<p>
  Hello <%= @current_user.name %>
  (<%= link_to 'Logout', session_path, method: :delete %>)!
</p>

<ul>
  <li><%= link_to 'Messages with live comments', messages_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Action Cable Examples</title>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
  <%= csrf_meta_tags %>
  <meta name="current-user" id="<%= @current_user.try(:id) %>">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<ul>
  <% @messages.each do |message| %>
    <li><%= link_to message.title, message %></li>
  <% end %>
</ul>

app/views/messages/show.html.erb
<h1><%= @message.title %></h1>

<p><%= @message.content %></p>

<%= render 'comments/comments', message: @message %>